language: python

cache: pip

matrix:
  include:
    - os: linux
      python: 3.5
      env: TOXENV=py35

    - os: linux
      python: 3.6
      env: TOXENV=py36

    - os: linux
      python: 3.7
      env: TOXENV=py37

    - os: linux
      python: 3.8
      env: TOXENV=py38

    - os: linux
      python: 3.9-dev
      env: TOXENV=py39

    - os: linux
      python: 3.7
      env: TOXENV=cov
      after_success:
        - travis_retry pip install codecov coveralls
        - codecov
        - coveralls

    - os: osx
      language: generic
      env: TOXENV=py37

install:
  - travis_retry bash -x .travis/install.sh

script:
  - tox

notifications:
  slack:
    secure: HH5RM0vObFrdQ0MBhwl/bdthcs9JQzCx+UUrjb8ojJVRbq71ZGqEWDWUa/qDvS3YjNbJsLfJq9IcF1B4juC1exI2DBTCZfxkHR7oXPemN0Oscs/AHsaD0NBFtDt1H4wXiGshbgeztk6MNJqFAqgIs2qQ1fb+SKnElRJgG9q3VZ/e92ZSNxc3/3ApM7qeQzC0FA9N7WCkdxrH6RT2+wFZucSM6JDo/7Ql34f22cgF8Da5D4UKE4V/55FB8enAeilwPv5HBNGQOmZHAZ432QP7V9a5SSycrji7SDySEyo2Gz9zwpXnYzejddm4/yN/yID6WtRHfbwgDbw4PsVWSJjWgARly0/pSCXMFZvUuMjQkcTCyvf5hB+2+c6XoGVHOvWYtiWUGFHPpBT45Ymsi4inY855lxT07BQeYCUDPBJQl+t2YnAIA/RKO5USirwDMsOqTcK4Sw3yQi6ESHo8z6Xfyepg0EbJS4yak++FA0GbzLLdyuNMdCQ0lLFUaHmNmQwr8xcoh1uJf68PjJPG5NnCZ/h9b9GcLFnLAOt1oeN+j0jIQOtqo1GuCiiaQ6ii3FAyIiUnTJE+lBKHio6yydN6nAdtTu3OPXc7GtgxQWapvsVpEkMcd5FSzCxf3UfVrtRzWTj+IxU8Lvd142Q7Z2SMLC42lM9rLhp266bxkpVBZDY=
